### ISSUE TITLE
Binance should support FastPass

### ISSUE THREAD

**Issue by awesomedash** [DashNetwork/dn-issues#15]
It has been a long-standing issues. Recently binance added the 1-confirmation support for Firo, which is a much smaller project. Supporting FastPass means 0-confirmation for Dash deposits.
See the recent discussion [here](https://discord.com/channels/484546513507188745/484546513935269918/808123892077297715).

**Comment by awesomedash** [comment]
New [post](https://www.dash.org/forum/threads/dash-vs-firo-on-binance.51309/) on Forum.

**Comment by vampyren** [comment]
Nice, we have it now both on forum and here. No one can say they are not aware :D 
Link to [forum](https://www.dash.org/forum/threads/dash-vs-firo-on-binance.51309/).

**Comment by awesomedash** [comment]
[Progress](https://discord.com/channels/484546513507188745/523262303433523200/808487936982515715): Deposits to Binance happen with one confirmation. \o/

**Comment by awesomedash** [comment]
Supporting ChainLocks is sufficient to be considered as a FastPass service. So, we can mark the first issue as FIXED.
